"""tests/integration/test_pipeline_smoke.py -- end-to-end smoke test.

Drives the full MVP pipeline on the synthetic flat_text.pdf fixture
generated by ``scripts/generate_fixtures.py``. Asserts:
    1. ``UIRV1.model_validate_json(...)`` succeeds.
    2. ``structure.root.children`` is non-empty.
    3. The first chunk has a 384-dim embedding attached.
    4. Total runtime < 60s on a warm cache.

Marked ``@pytest.mark.slow`` (auto-applied via conftest) so the default
``pytest`` invocation excludes this. Run explicitly with:

    pytest -m slow tests/integration/test_pipeline_smoke.py
"""
from __future__ import annotations

import time
from pathlib import Path
import pytest


FIXTURE_PATH = (
    Path(__file__).parent.parent / "fixtures" / "sample_pdfs" / "flat_text.pdf"
)


def _ensure_fixture_present() -> None:
    """Generate the fixture if missing (cold dev machine, first run)."""
    if FIXTURE_PATH.is_file():
        return
    # Invoke the generator via a subprocess to avoid importing reportlab here.
    import subprocess
    import sys
    script = Path(__file__).parent.parent.parent / "scripts" / "generate_fixtures.py"
    subprocess.check_call([sys.executable, str(script)])


def test_pipeline_smoke_on_flat_text(tmp_path: Path) -> None:
    """Drive the orchestrator on the flat_text fixture and validate the UIR."""
    _ensure_fixture_present()
    if not FIXTURE_PATH.is_file():
        pytest.skip(f"fixture not present at {FIXTURE_PATH}")

    from uir_pipeline.pipeline import run
    from uir_pipeline.uir_schema import UIRV1

    t0 = time.monotonic()
    result = run(
        FIXTURE_PATH,
        output_dir=tmp_path,
        skip_weaviate=True,  # smoke test focuses on JSON output
        with_embeddings=True,
    )
    elapsed = time.monotonic() - t0
    print(f"\n[smoke] elapsed={elapsed:.2f}s chunks={result.chunk_count} entities={result.entity_count}")

    # JSON was written.
    assert result.out_path.is_file()

    # JSON validates against UIRV1.
    parsed = UIRV1.model_validate_json(result.out_path.read_text())

    # Structure is non-empty.
    assert parsed.structure.root.children, "no chunk children emitted"

    # At least one chunk has a 384-dim embedding attached.
    vectors = [cn.modal_features.get("vector") for cn in parsed.structure.root.children]
    vectors = [v for v in vectors if v is not None]
    assert vectors, "no chunks have embeddings"
    assert any(v.get("dim") == 384 for v in vectors)

    # Sanity: provenance populated.
    assert parsed.provenance.extraction.model == "LayoutLMv3-heuristic"
    assert parsed.provenance.normalization.version == "1.0"


def test_pipeline_emits_zero_chunks_on_empty_pdf(tmp_path: Path) -> None:
    """An empty (whitespace-only) PDF should still produce a valid UIRV1 JSON.

    We construct a 1-page PDF with a single empty paragraph so the
    orchestrator's text extraction returns an empty string and the
    chunker produces no chunks. The output JSON is still valid.
    """
    import io
    from pypdf import PdfWriter
    from pypdf.generic import RectangleObject

    # Generate a minimal 1-page PDF via pypdf (no reportlab dep).
    w = PdfWriter()
    w.add_blank_page(width=612, height=792)
    pdf_bytes = io.BytesIO()
    w.write(pdf_bytes)
    pdf_path = tmp_path / "empty.pdf"
    pdf_path.write_bytes(pdf_bytes.getvalue())

    from uir_pipeline.pipeline import run
    from uir_pipeline.uir_schema import UIRV1

    result = run(pdf_path, output_dir=tmp_path, skip_weaviate=True)
    parsed = UIRV1.model_validate_json(result.out_path.read_text())
    # Empty PDF -> no chunks emitted -> root has no children.
    assert parsed.structure.root.children == []
